### ISSUE TITLE
レポジトリ名、文章名を変更する

### ISSUE THREAD

**Issue by nsakuraya** [namo-namo/implementation#3]
spec ＝仕様には、技術的な詳細を書かないほうがよいのではないでしょうか？

仕様にはより簡潔に、サービス全体の説明を記載し、技術的な実現方法は別の文章で管理したほうがいいと思います。

なぜなら、技術的な実現方法はその時々で最適なものが異なるからです。例えば速いWebページを実現するためには、現在は SPA や静的ページ生成が最適かもしれませんが、将来は違うかもしれません。しかし、速いページであること、どれくらい速いのか、どのようなユーザ体験ができるのかなどの仕様は変わりません。そして後者のユーザ体験の記載のほうが重要で上位にあるべきです。

技術的な実現方法は、仕様を実現するためのその時々の最適な方法を記載する文章として別に管理するほうが、変化に強いサービスになるはずです。

**Comment by x-sid-122** [comment]
レポジトリ名を **implementation** に変更し、README の記載を変更しました。

**Comment by x-sid-122** [comment]
spec.git という新しいレポジトリを作成しました。仕様の記載をお願いします。
